# https://circleci.com/docs/language-javascript/
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  node: circleci/node@5.0.2

jobs:
  pipeline-job: # this can be any name you choose
    executor: node/default # use the default executor defined within the circleci/node@5.0.2 orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          command: npm run lint
          name: Lint app
      - run:
          command: npm run build
          name: Build app
      - run:
          command: npm run test
          name: Run tests
      - run:
          name: Code Climate Test Coverage
          command: |
            ./cc-test-reporter before-build
            npm run codeCoverage
            ./cc-test-reporter format-coverage -t clover coverage/clover.xml --output coverage/codeclimate.json
            cp coverage/clover.xml .     
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-artifacts
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  pipeline-workflow: # this can be any name you choose
    jobs:
      - pipeline-job