# npm version patch

# https://circleci.com/docs/language-javascript/
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  node: circleci/node@5.0.2

jobs:
  pipeline-job: # this can be any name you choose
    executor: node/default # use the default executor defined within the circleci/node@5.0.2 orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Lint app
      - run:
          command: npm run build
          name: Build app
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run codeCoverage
          name: Check code coverage
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  pipeline-workflow: # this can be any name you choose
    jobs:
      - pipeline-job